import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const TOKENS_PATH = resolve(__dirname, '../tokens/tokens.json');
const OUTPUT_DIR = resolve(__dirname, '../src/tokens');

// Ensure output directory exists
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Transform tokens from Tokens Studio format to Style Dictionary format
function transformTokens(tokens: Record<string, unknown>, prefix = ''): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(tokens)) {
    const path = prefix ? `${prefix}.${key}` : key;

    if (value && typeof value === 'object' && '$value' in value) {
      // It's a token
      const token = value as { $value: unknown; $type?: string };
      let tokenValue = token.$value;

      // Resolve references
      if (typeof tokenValue === 'string' && tokenValue.startsWith('{') && tokenValue.endsWith('}')) {
        tokenValue = tokenValue.slice(1, -1); // Remove { }
      }

      result[key] = {
        value: tokenValue,
        type: token.$type,
        original: token,
      };
    } else if (value && typeof value === 'object') {
      // It's a group
      result[key] = transformTokens(value as Record<string, unknown>, path);
    }
  }

  return result;
}

// Read and transform tokens
const rawTokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf-8'));
const transformedTokens = transformTokens(rawTokens);

// Write transformed tokens for debugging
writeFileSync(
  resolve(OUTPUT_DIR, 'tokens-transformed.json'),
  JSON.stringify(transformedTokens, null, 2)
);

// Configure Style Dictionary
const sd = new StyleDictionary({
  tokens: transformedTokens,
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: `${OUTPUT_DIR}/`,
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: `${OUTPUT_DIR}/`,
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: `${OUTPUT_DIR}/`,
      files: [
        {
          destination: 'tokens.ts',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
  },
});

// Build all platforms
await sd.buildAllPlatforms();

// Generate index.ts for tokens
const indexContent = `// Auto-generated by build-tokens.ts
// Do not edit directly

export * from './tokens';
import './variables.css';

// Re-export CSS variables path for consumers
export const cssVariablesPath = new URL('./variables.css', import.meta.url).href;
`;

writeFileSync(resolve(OUTPUT_DIR, 'index.ts'), indexContent);

console.log('✅ Tokens built successfully!');
console.log(`   CSS: ${OUTPUT_DIR}/variables.css`);
console.log(`   JS:  ${OUTPUT_DIR}/tokens.js`);
console.log(`   TS:  ${OUTPUT_DIR}/tokens.ts`);
