// This file is auto-generated by the build:tokens script
// Run `npm run build:tokens` to generate the actual tokens

// Placeholder exports - will be replaced by build
export const tokens = {};

// Re-export generated tokens when available
// export * from './tokens';
